[chs startActionId="1"]
    [action id="1" nextActionId="3" roundId="1"]
        [bg src="时光素材-日式唯美动漫场景  (1)" layer="Background1"]
        [fg src="主角全身1" layer="Foreground1"]
        [bgm src="Sandbox External Music_Air Apparent_All By Yourself (ft. Krista Youngs and Julia Ross) - Instrumental_(Instrumental Version)" volume="90" loop action="play"]
        [line actor="女の子" line="hello hello are you okay???" voice="hello" fsize="15" linespacing="15" fcolor="0x6079d2ff" fstyle="Italic"]
        [line actor="朋也" line="yeah yeah" voice="yeah" fsize="15" linespacing="15" fcolor="0x6079d2ff" fstyle="Italic"]
        [line actor="女の子" line="Okay sounds fine" voice="okay" fsize="15" linespacing="15" fcolor="0x6079d2ff" fstyle="Italic"]
    [action]
    [action id="3" nextActionId="4" previousActionId="1" roundId="1"]
        [line actor="朋也" line="......" fcolor="0x7f3d65ff"]
    [action]
    [action id="4" nextActionId="5" previousActionId="3" roundId="1"]
        [bg src="时光素材-日式唯美动漫场景  (2)" layer="Background1"]
        [fg src="少爷1" layer="Foreground1"]
    [action]
    [action id="5" nextActionId="7" previousActionId="4" roundId="1"]
        [bgm src="Sandbox External Music_ELYAZ_The Place Where We Belong_(Original)" loop action="play"]
    [action]
    [action id="7" nextActionId="8" previousActionId="5" roundId="1"]
        [select id="selector-1" type="horizontal"]
            [option text="Choice 1"]
                [line actor="朋也" line="from the male side"]
            [option]
            [option text="Choice 2"]
                [line actor="女の子" line="from the female side"]
            [option]
        [select]
    [action]
    [action id="8" previousActionId="7" roundId="1"]
        [judge id="judge-1"]
            [event evtid="10000"]
            [event]
            [group id="group-1"]
                [pair name="HP" value="15"]
                [pair name="MP" value="10"]
            [group]
        [judge]
    [action]
[che]
